"""Prompt templates for AI calls."""

from scd.ai.prompts.dir_summary import (
    DIR_SUMMARY_LEAF_SYSTEM,
    DIR_SUMMARY_LEAF_USER,
    DIR_SUMMARY_PARENT_SYSTEM,
    DIR_SUMMARY_PARENT_USER,
)
from scd.ai.prompts.directory_match import DIRECTORY_MATCH_SYSTEM, DIRECTORY_MATCH_USER
from scd.ai.prompts.function_compare import FUNCTION_COMPARE_SYSTEM, FUNCTION_COMPARE_USER

__all__ = [
    "DIR_SUMMARY_LEAF_SYSTEM",
    "DIR_SUMMARY_LEAF_USER",
    "DIR_SUMMARY_PARENT_SYSTEM",
    "DIR_SUMMARY_PARENT_USER",
    "DIRECTORY_MATCH_SYSTEM",
    "DIRECTORY_MATCH_USER",
    "FUNCTION_COMPARE_SYSTEM",
    "FUNCTION_COMPARE_USER",
]
